### ISSUE TITLE
Page Gap Configuration

### ISSUE THREAD

**Issue by hugs7** [hugs7/tiptap-extension-pagination#31]
As per #20 , would be good to have a user-customisable page gap as a configuration option rather than relying on

```scss
.tiptap {
    min-height: calc(100vh - 2rem);

    &:focus-visible {
        outline: none;
    }

    > * + * {
        margin-top: 0.75em;
    }

   ...
}
```
